CREATE TABLE "admin"."user" (
	username varchar NOT NULL,
	"password" varchar NOT NULL,
	createddate timestamp NULL
);
ALTER TABLE "admin"."user" ALTER COLUMN createddate SET DEFAULT now();

CREATE TABLE admin.chatBot (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_name CHARACTER VARYING NOT NULL,
	collection_name CHARACTER VARYING NOT NULL,
	folder_name CHARACTER VARYING NOT null,
UNIQUE(event_name,collection_name));

ALTER TABLE "admin".chatbot ADD chatboturl varchar NULL;

CREATE TABLE admin.chatHistory (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	query CHARACTER VARYING NOT NULL,
	response CHARACTER VARYING NOT NULL,
	collection_name CHARACTER VARYING NOT null);

CREATE TABLE admin.generated_questions (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	query CHARACTER VARYING NOT NULL,
	response CHARACTER VARYING NOT NULL,
	collection_name CHARACTER VARYING NOT null);

ALTER TABLE "admin".generated_questions ALTER COLUMN response DROP NOT NULL;
ALTER TABLE "admin".chatbot ADD question_generted boolean DEFAULT false NULL;


